"""The Python QR encoder must draw exactly the modules web/vendor/qrcodegen.js draws (vectors generated by
scripts/gen_qr_vectors.js), so terminal mode and the browser sender produce the same codes."""
import json
import pathlib
import sys
import unittest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from qbeam import qr  # noqa: E402

VECTORS = json.loads((pathlib.Path(__file__).parent / "data" / "qr_vectors.json").read_text(encoding="utf-8"))


class QrVectorTest(unittest.TestCase):
    def test_matches_qrcodegen(self):
        for v in VECTORS:
            with self.subTest(version=v["version"], ecc=v["ecc"], mask=v["mask"], length=len(v["dataHex"]) // 2):
                grid = qr.encode(bytes.fromhex(v["dataHex"]), v["version"], v["ecc"], v["mask"])
                rows = ["".join("1" if d else "0" for d in row) for row in grid]
                diff = sum(a != b for ra, rb in zip(rows, v["rows"]) for a, b in zip(ra, rb))
                self.assertEqual(diff, 0, f"{diff} modules differ")

    def test_capacity_matches_presets(self):
        self.assertEqual([qr.capacity(v) for v in (25, 30, 40)], [1273, 1732, 2953])
        self.assertEqual(qr.capacity(40, "M"), 2331)

    def test_too_long_raises(self):
        with self.assertRaises(ValueError):
            qr.encode(bytes(qr.capacity(5) + 1), 5)


if __name__ == "__main__":
    unittest.main()
